-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, T.CATEGORY, SUM(T.TOTAL_SALES) AS TOTAL_SALES
FROM (SELECT B.BOOK_ID, B.CATEGORY, B.AUTHOR_ID, (BS.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK B, BOOK_SALES BS
WHERE B.BOOK_ID = BS.BOOK_ID 
AND BS.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31') T, AUTHOR A
WHERE A.AUTHOR_ID = T.AUTHOR_ID
GROUP BY A.AUTHOR_ID, T.CATEGORY
ORDER BY A.AUTHOR_ID, T.CATEGORY DESC